# Travis-CI configuration file

branches:
  except:
    - master

sudo: false

# language settings
language: python

# listing the Python versions to be tested
python:
  - "3.9"

# install specific dependencies for the execution of src
# TODO: manage this in a requirements-file (requirements/travis.txt)?
install:
  - pip install pipenv --upgrad
  - pipenv install --system

# run the src
# relying on tox (see tox.ini); tox-travis will take care of management details
script:
  - tox

# after running the src (with coverage), report to coveralls
after_success:
  - coverage combine --append
  - coverage report
  - coveralls